# ==========================================
# FinTegrity Spring Boot Properties configuration
# ==========================================

# Port Configuration
server.port=8080

# PostgreSQL JDBC DataSource Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8r4tbb7uimc73emms3g-a.oregon-postgres.render.com/fintegrity_db
spring.datasource.username=fintegrity_db_user
spring.datasource.password=WlrLe1DonOxVvnaHMdgrCUnLFyV0vMdz
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging levels
logging.level.org.springframework.web=INFO
logging.level.com.fintegrity=DEBUG
